services:
  - type: web
    name: corretor-de-arquivos-api
    env: docker
    rootDir: unimed-tools-backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: AUTH_MFA_ENCRYPTION_KEY
        sync: false
      - key: REPORT_SCHEDULE_ENCRYPTION_KEY
        sync: false
      - key: AUTH_COOKIE_SECURE
        value: true
      - key: SGU_API_KEY
        sync: false
      - key: SGU_API_BASE_URL
        value: https://api.lorena.sgusuite.com.br
      - key: SGU_API_KEY_HEADERS
        value: apikey,x-api-key
      - key: SGU_API_PROCEDURE_PATH
        value: /api/procedure/p_prcssa_dados
      - key: SGU_API_EXECUTION_PATH
        value: /api/procedure/p_prcssa_dados
