import { ToolDefinition } from '../models/tool.model';

export const CORE_TOOLS: readonly ToolDefinition[] = [
  {
    id: 'comercial',
    nome: 'Comercial',
    categoria: 'Empresas e contratos',
    descricao: 'Beneficiários, receita, despesas e faixa etária por empresa em um fluxo único.',
    route: '/comercial',
    icon: 'comercial',
    permission: 'COMERCIAL_ACESSAR',
    keywords: ['empresa', 'beneficiario', 'receita', 'despesa', 'faixa etaria', 'comercial'],
    kind: 'native',
  },
  {
    id: 'assistencial',
    nome: 'Assistencial',
    categoria: 'Relatório sob medida',
    descricao: 'Escolha colunas, configure filtros, salve modelos e gere relatórios assistenciais.',
    route: '/assistencial',
    icon: 'assistencial',
    permission: 'ASSISTENCIAL_ACESSAR',
    keywords: ['personalizado', 'colunas', 'filtros', 'assistencial', 'despesa'],
    kind: 'native',
  },
  {
    id: 'revisao-contas',
    nome: 'Revisão de Contas',
    categoria: 'XML TISS',
    descricao: 'Analise e corrija arquivos XML em lote, com revisão detalhada das alterações.',
    route: '/revisao-contas',
    icon: 'revisao',
    permission: 'REVISAO_CONTAS_ACESSAR',
    keywords: ['xml', 'tiss', 'revisao', 'contas', 'lote'],
    kind: 'native',
  },
  {
    id: 'unica',
    nome: 'Única',
    categoria: 'Rede ANS',
    descricao: 'Corrija arquivos posicionais de rede usando a planilha de referência.',
    route: '/unica',
    icon: 'unica',
    permission: 'UNICA_ACESSAR',
    keywords: ['ans', 'rede', 'rps', 'unica', 'cnes', 'cnpj'],
    kind: 'native',
  },
  {
    id: 'hospital',
    nome: 'Hospital',
    categoria: 'Autorizações',
    descricao: 'Consulte solicitações ainda não convertidas em guia e filtre por beneficiário, convênio e procedimento.',
    route: '/hospital',
    icon: 'hospital',
    permission: 'HOSPITAL_ACESSAR',
    keywords: ['hospital', 'autorizacao', 'guia', 'procedimento', 'convenio'],
    kind: 'native',
  },
  {
    id: 'gestao-risco',
    nome: 'Gestão de Risco',
    categoria: 'Indicadores e rastreios',
    descricao: 'Gere e confira os relatórios de colonoscopia, consultas, mamografia, ressonância e sangue oculto.',
    route: '/gestao-risco',
    icon: 'risco',
    permission: 'GESTAO_RISCO_ACESSAR',
    keywords: ['risco', 'ramiro', 'mamografia', 'colonoscopia', 'ressonancia', 'sangue oculto'],
    kind: 'native',
  },
  {
    id: 'valorizar-guias-fusex-spa',
    nome: 'Valorizar guias Fusex-SPA',
    categoria: 'Guias e faturamento',
    descricao: 'Valide guias para valorização de honorários. Execução aguardando homologação da integração SGU.',
    route: '/valorizar-guias-fusex-spa',
    icon: 'hospital',
    permission: 'FUSEX_SPA_VALORIZAR',
    keywords: ['fusex', 'spa', 'guias', 'honorarios', 'valorizar'],
    kind: 'native',
  },
  {
    id: 'ti',
    nome: 'TI',
    categoria: 'Administração da plataforma',
    descricao: 'Gerencie APIs, grupos de relatórios, ferramentas e novos cards da aplicação.',
    route: '/ti',
    icon: 'ti',
    adminOnly: true,
    keywords: ['ti', 'api', 'relatorios', 'ferramentas', 'administracao'],
    kind: 'native',
  },
] as const;
