package com.unimedlorena.tools.service;

/**
 * Fragmentos SQL estáticos usados pelo relatório personalizado.
 *
 * O builder permanece responsável por composição e validação; esta classe
 * concentra somente os blocos SQL base extensos.
 */
final class RelatorioPersonalizadoSqlFragments {

  private RelatorioPersonalizadoSqlFragments() {
  }

  static final String CTE_SQL = """
      WITH SOLA_UNICA AS (
        SELECT *
        FROM (
          SELECT SOLA.*,
            ROW_NUMBER() OVER (
              PARTITION BY SOLA.GSOL_COD_UNIMED_BNF,
                SOLA.GSOL_COD_CNTRAT_CART_BNF,
                SOLA.GSOL_COD_BNF,
                SOLA.GSOL_COD_DEPNTE_BNF,
                SOLA.GSOL_NRO_SENHA
              ORDER BY SOLA.GSOL_COD_SOLICITACAO DESC
            ) RN
          FROM DBAUNIMED.GUIA_SOLIC_AUTRIZ SOLA
        )
        WHERE RN = 1
      ),
      SOL_UNICA AS (
        SELECT *
        FROM (
          SELECT SOL.*,
            ROW_NUMBER() OVER (
              PARTITION BY SOL.NR_GUIA
              ORDER BY SOL.CD_SOLICITACAO DESC
            ) RN
          FROM DATACENTER.AUTSC2_SOLICITACOES SOL
        )
        WHERE RN = 1
      ),
      ESP_FORA_REDE_UNICA AS (
        SELECT *
        FROM (
          SELECT ESP.*,
            ROW_NUMBER() OVER (
              PARTITION BY ESP.ESPMD_COD_NRO_CBO
              ORDER BY ESP.ESPMD_COD
            ) RN
          FROM DBAUNIMED.ESPEC_MEDICA ESP
        )
        WHERE RN = 1
      )
      """.strip();

  static final String CTE_INDICADORES_SQL = """
      WITH FATURA_INDICADOR AS (
        SELECT
          FR.FR_NRO,
          FR.FR_DAT_COMPET,
          FR.FR_COD_EMP_CONTRT_BASE
        FROM DBAUNIMED.FATURA_REC FR
        WHERE FR.FR_DAT_CANCEL = DATE '0001-01-01'
          /*FILTRO_COMPETENCIA_FATURA*/
      ),
      MOVIMENTO_RECEITA AS (
        SELECT
          MR.MR_COD,
          MR.MR_COD_UNIMED_BNFRIO,
          MR.MR_COD_CNTRAT_CART_BNFRIO,
          MR.MR_COD_BNFRIO,
          MR.MR_COD_DEPNTE_BNFRIO,
          MR.MR_NRO_CNTRAT_VENDA,
          FR.FR_DAT_COMPET,
          FR.FR_COD_EMP_CONTRT_BASE
        FROM DBAUNIMED.MVTO_REC MR
        INNER JOIN FATURA_INDICADOR FR ON FR.FR_NRO = MR.MR_FR_NRO
      ),
      RECEITA_TAXA AS (
        SELECT
          MRT.MR_COD,
          SUM(NVL(MRT.MRT_VAL_FINAL, 0)) AS VALOR_MENSALIDADE
        FROM DBAUNIMED.MVTO_REC_TAXA MRT
        INNER JOIN MOVIMENTO_RECEITA MOV ON MOV.MR_COD = MRT.MR_COD
        GROUP BY MRT.MR_COD
      ),
      RECEITA_SERVICO AS (
        SELECT
          MRS.MR_COD,
          SUM(NVL(MRS.MRS_VAL_FINAL, 0)) AS VALOR_COPART,
          SUM(
            CASE WHEN NVL(MRS.MRS_VAL_FINAL, 0) > 0
              THEN MRS.MRS_VAL_FINAL ELSE 0 END
          ) AS VALOR_COPART_SINISTRO
        FROM DBAUNIMED.MVTO_REC_SERVIC MRS
        INNER JOIN MOVIMENTO_RECEITA MOV ON MOV.MR_COD = MRS.MR_COD
        GROUP BY MRS.MR_COD
      ),
      DESPESA_INDICADOR AS (
        SELECT
          GUIA.GUIA_COD_UNIMED_BNFRIO,
          GUIA.GUIA_COD_CNTRAT_CART_BNFRIO,
          GUIA.GUIA_COD_BNFRIO,
          GUIA.GUIA_COD_DEPNTE_BNFRIO,
          GUIA.GUIA_NRO_COMPET,
          BNF.CV_NRO,
          CNT_BASE.EMPCN_COD,
          SUM(
            NVL(ITEM_GUIA.GUITE_VAL_PAG_HONOR, 0) +
            NVL(ITEM_GUIA.GUITE_VAL_PAG_FILME, 0) +
            NVL(ITEM_GUIA.GUITE_VAL_PAG_CO, 0)
          ) AS VALOR_DESPESA,
          0 AS VALOR_RECEITA,
          0 AS VALOR_MENSALIDADE,
          0 AS VALOR_COPART
        FROM DBAUNIMED.GUIA GUIA
        INNER JOIN DBAUNIMED.GUIA_ITEM ITEM_GUIA
          ON ITEM_GUIA.GUIA_COD_ID = GUIA.GUIA_COD_ID
        LEFT JOIN DBAUNIMED.BNFRIO BNF
          ON BNF.UNI_COD_RESPON = GUIA.GUIA_COD_UNIMED_BNFRIO
          AND BNF.BNF_COD_CNTRAT_CART = GUIA.GUIA_COD_CNTRAT_CART_BNFRIO
          AND BNF.BNF_COD = GUIA.GUIA_COD_BNFRIO
          AND BNF.BNF_COD_DEPNTE = GUIA.GUIA_COD_DEPNTE_BNFRIO
        LEFT JOIN DBAUNIMED.CNTRAT_VENDA CNT_BASE ON CNT_BASE.CV_NRO = BNF.CV_NRO
        WHERE ITEM_GUIA.GUITE_IND_STATUS = 'I'
          /*FILTRO_COMPETENCIA_DESPESA*/
        GROUP BY
          GUIA.GUIA_COD_UNIMED_BNFRIO,
          GUIA.GUIA_COD_CNTRAT_CART_BNFRIO,
          GUIA.GUIA_COD_BNFRIO,
          GUIA.GUIA_COD_DEPNTE_BNFRIO,
          GUIA.GUIA_NRO_COMPET,
          BNF.CV_NRO,
          CNT_BASE.EMPCN_COD
      ),
      RECEITA_INDICADOR AS (
        SELECT
          MR.MR_COD_UNIMED_BNFRIO AS GUIA_COD_UNIMED_BNFRIO,
          MR.MR_COD_CNTRAT_CART_BNFRIO AS GUIA_COD_CNTRAT_CART_BNFRIO,
          MR.MR_COD_BNFRIO AS GUIA_COD_BNFRIO,
          MR.MR_COD_DEPNTE_BNFRIO AS GUIA_COD_DEPNTE_BNFRIO,
          MR.FR_DAT_COMPET AS GUIA_NRO_COMPET,
          MR.MR_NRO_CNTRAT_VENDA AS CV_NRO,
          MR.FR_COD_EMP_CONTRT_BASE AS EMPCN_COD,
          0 AS VALOR_DESPESA,
          SUM(NVL(RT.VALOR_MENSALIDADE, 0) + NVL(RS.VALOR_COPART, 0)) AS VALOR_RECEITA,
          SUM(NVL(RT.VALOR_MENSALIDADE, 0)) AS VALOR_MENSALIDADE,
          SUM(NVL(RS.VALOR_COPART_SINISTRO, 0)) AS VALOR_COPART
        FROM MOVIMENTO_RECEITA MR
        LEFT JOIN RECEITA_TAXA RT ON RT.MR_COD = MR.MR_COD
        LEFT JOIN RECEITA_SERVICO RS ON RS.MR_COD = MR.MR_COD
        WHERE NVL(RT.VALOR_MENSALIDADE, 0) <> 0
          OR NVL(RS.VALOR_COPART, 0) <> 0
        GROUP BY
          MR.MR_COD_UNIMED_BNFRIO,
          MR.MR_COD_CNTRAT_CART_BNFRIO,
          MR.MR_COD_BNFRIO,
          MR.MR_COD_DEPNTE_BNFRIO,
          MR.FR_DAT_COMPET,
          MR.MR_NRO_CNTRAT_VENDA,
          MR.FR_COD_EMP_CONTRT_BASE
      ),
      RECEITA_SEM_MOVIMENTO AS (
        SELECT
          CAST(NULL AS NUMBER) AS GUIA_COD_UNIMED_BNFRIO,
          CAST(NULL AS NUMBER) AS GUIA_COD_CNTRAT_CART_BNFRIO,
          CAST(NULL AS NUMBER) AS GUIA_COD_BNFRIO,
          CAST(NULL AS NUMBER) AS GUIA_COD_DEPNTE_BNFRIO,
          FR.FR_DAT_COMPET AS GUIA_NRO_COMPET,
          CAST(NULL AS NUMBER) AS CV_NRO,
          FR.FR_COD_EMP_CONTRT_BASE AS EMPCN_COD,
          0 AS VALOR_DESPESA,
          SUM(NVL(FRI.FRI_VAL_FINAL, 0)) AS VALOR_RECEITA,
          0 AS VALOR_MENSALIDADE,
          0 AS VALOR_COPART
        FROM DBAUNIMED.FATURA_REC_ITEM FRI
        INNER JOIN FATURA_INDICADOR FR ON FR.FR_NRO = FRI.FR_NRO
        WHERE FRI.FRI_COD_MVTO_REC IS NULL
        GROUP BY FR.FR_DAT_COMPET, FR.FR_COD_EMP_CONTRT_BASE
      ),
      INDICADOR_BASE AS (
        SELECT * FROM DESPESA_INDICADOR
        UNION ALL
        SELECT * FROM RECEITA_INDICADOR
        UNION ALL
        SELECT * FROM RECEITA_SEM_MOVIMENTO
      ),
      ENDERECO_ATIVO AS (
        SELECT *
        FROM (
          SELECT
            PE_BASE.*,
            ROW_NUMBER() OVER (
              PARTITION BY PE_BASE.PES_COD
              ORDER BY
                CASE WHEN PE_BASE.CEP_COD IS NOT NULL THEN 0 ELSE 1 END,
                CASE WHEN PE_BASE.END_COD_UF IS NOT NULL THEN 0 ELSE 1 END,
                PE_BASE.END_NRO
            ) RN
          FROM DBAUNIMED.PESSOA_END PE_BASE
          WHERE PE_BASE.END_DAT_EXCL IS NULL
            OR TRUNC(PE_BASE.END_DAT_EXCL) = DATE '0001-01-01'
        )
        WHERE RN = 1
      )
      """.strip();

  static final String FROM_INDICADORES_SQL = """
      FROM INDICADOR_BASE G
      LEFT JOIN DBAUNIMED.BNFRIO BF
        ON G.GUIA_COD_UNIMED_BNFRIO = BF.UNI_COD_RESPON
        AND G.GUIA_COD_CNTRAT_CART_BNFRIO = BF.BNF_COD_CNTRAT_CART
        AND G.GUIA_COD_BNFRIO = BF.BNF_COD
        AND G.GUIA_COD_DEPNTE_BNFRIO = BF.BNF_COD_DEPNTE
      /*JOIN_GRUPO_BENEFICIARIO*/
      LEFT JOIN DBAUNIMED.PESSOA P ON P.PES_COD = BF.BNF_COD_PESSOA
      LEFT JOIN DBAUNIMED.PESSOA_DOC PESDOC
        ON PESDOC.PES_COD = P.PES_COD AND PESDOC.TPDOC_COD = 2
      LEFT JOIN DBAUNIMED.CNTRAT_VENDA CNT ON CNT.CV_NRO = NVL(G.CV_NRO, BF.CV_NRO)
      LEFT JOIN DBAUNIMED.EMP_CONTRT EC
        ON EC.EMPCN_COD = NVL(G.EMPCN_COD, CNT.EMPCN_COD)
      LEFT JOIN DBAUNIMED.PESSOA PES_EMPRESA ON PES_EMPRESA.PES_COD = EC.EMPCN_COD_PESSOA
      LEFT JOIN DBAUNIMED.PLANO PN ON PN.PLANO_NRO_REG_ANS = CNT.PLANO_NRO_REG_ANS
      LEFT JOIN ENDERECO_ATIVO PE ON PE.PES_COD = P.PES_COD
      LEFT JOIN ENDERECO_ATIVO PE_TIT ON PE_TIT.PES_COD = PE.END_COD_PES_VINC
      LEFT JOIN DBAUNIMED.CEP CEP ON CEP.CEP_COD = NVL(PE.CEP_COD, PE_TIT.CEP_COD)
      LEFT JOIN DBAUNIMED.CIDADE CIDADE ON CIDADE.CIDAD_COD = CEP.CIDAD_COD
      LEFT JOIN DBAUNIMED.US8001 EXT
        ON EXT.US8UNIMED = G.GUIA_COD_UNIMED_BNFRIO
        AND EXT.US8CODCONT = G.GUIA_COD_CNTRAT_CART_BNFRIO
        AND EXT.US8CODUSU = G.GUIA_COD_BNFRIO
        AND EXT.US8CODDEP = G.GUIA_COD_DEPNTE_BNFRIO
      LEFT JOIN DBAUNIMED.UNIMED U_INTERCAMBIO ON U_INTERCAMBIO.UNI_COD = EXT.US8UNIMED
      LEFT JOIN DBAUNIMED.PESSOA PES_INTERCAMBIO
        ON PES_INTERCAMBIO.PES_COD = U_INTERCAMBIO.UNI_PES_COD
      WHERE 1 = 1
      """.strip();

  static final String FROM_BASE_SQL = """
      FROM DBAUNIMED.GUIA G
      LEFT JOIN DBAUNIMED.BNFRIO BF
        ON G.GUIA_COD_UNIMED_BNFRIO = BF.UNI_COD_RESPON
        AND G.GUIA_COD_CNTRAT_CART_BNFRIO = BF.BNF_COD_CNTRAT_CART
        AND G.GUIA_COD_BNFRIO = BF.BNF_COD
        AND G.GUIA_COD_DEPNTE_BNFRIO = BF.BNF_COD_DEPNTE
      /*JOIN_GRUPO_BENEFICIARIO*/
      LEFT JOIN DBAUNIMED.PESSOA P ON P.PES_COD = BF.BNF_COD_PESSOA
      LEFT JOIN DBAUNIMED.PESSOA_DOC PESDOC
        ON PESDOC.PES_COD = P.PES_COD AND PESDOC.TPDOC_COD = 2
      LEFT JOIN DBAUNIMED.CNTRAT_VENDA CNT ON CNT.CV_NRO = BF.CV_NRO
      LEFT JOIN DBAUNIMED.EMP_CONTRT EC ON EC.EMPCN_COD = CNT.EMPCN_COD
      LEFT JOIN DBAUNIMED.PESSOA PES_EMPRESA ON PES_EMPRESA.PES_COD = EC.EMPCN_COD_PESSOA
      LEFT JOIN DBAUNIMED.PLANO PN ON PN.PLANO_NRO_REG_ANS = CNT.PLANO_NRO_REG_ANS
      LEFT JOIN DBAUNIMED.PREST PR_GUIA ON PR_GUIA.PREST_COD = G.GUIA_COD_PREST
      LEFT JOIN DBAUNIMED.GRUPO_PREST GP ON GP.GRPRE_COD = PR_GUIA.PREST_COD_GRUPO
      LEFT JOIN SOLA_UNICA SOLA
        ON SOLA.GSOL_NRO_SENHA = G.GUIA_NRO_SENHA_SOLIC
        AND SOLA.GSOL_COD_UNIMED_BNF = G.GUIA_COD_UNIMED_BNFRIO
        AND SOLA.GSOL_COD_CNTRAT_CART_BNF = G.GUIA_COD_CNTRAT_CART_BNFRIO
        AND SOLA.GSOL_COD_BNF = G.GUIA_COD_BNFRIO
        AND SOLA.GSOL_COD_DEPNTE_BNF = G.GUIA_COD_DEPNTE_BNFRIO
        AND G.GUIA_IND_REEMB = 'N'
        AND G.GUIA_COD_GFR_ID IS NULL
      LEFT JOIN SOL_UNICA SOL
        ON SOL.NR_GUIA = G.GUIA_COD
        AND G.GUIA_IND_REEMB = 'N'
        AND G.GUIA_COD_GFR_ID IS NULL
      LEFT JOIN DBAUNIMED.GUIA_ITEM GI ON GI.GUIA_COD_ID = G.GUIA_COD_ID
      LEFT JOIN DBAUNIMED.GUIA_CID GC ON GC.GUIA_COD_ID = G.GUIA_COD_ID
      LEFT JOIN DBAUNIMED.ITEM IT ON IT.ITEM_COD = GI.ITEM_COD
      LEFT JOIN DBAUNIMED.MVTO_REC_SERVIC MVTOSER
        ON MVTOSER.GUIA_COD_ID = G.GUIA_COD_ID
        AND MVTOSER.GUITE_NRO_SEQ = GI.GUITE_NRO_SEQ
      INNER JOIN DBAUNIMED.MVTO_REC MVTOR ON MVTOR.MR_COD = MVTOSER.MR_COD
      LEFT JOIN DBAUNIMED.FATURA_REC FAT ON FAT.FR_NRO = MVTOR.MR_FR_NRO
      LEFT JOIN DBAUNIMED.PESSOA_END PE
        ON PE.PES_COD = P.PES_COD
        AND (PE.END_DAT_EXCL IS NULL OR TRUNC(PE.END_DAT_EXCL) = DATE '0001-01-01')
      LEFT JOIN DBAUNIMED.BNFRIO BF_TIT
        ON BF_TIT.UNI_COD_RESPON = BF.UNI_COD_RESPON
        AND BF_TIT.BNF_COD_CNTRAT_CART = BF.BNF_COD_CNTRAT_CART
        AND BF_TIT.BNF_COD = BF.BNF_COD
        AND BF_TIT.BNF_COD_DEPNTE = 0
      LEFT JOIN DBAUNIMED.PESSOA_END PE_TIT
        ON PE_TIT.PES_COD = NVL(PE.END_COD_PES_VINC, BF_TIT.BNF_COD_PESSOA)
        AND (PE_TIT.END_DAT_EXCL IS NULL OR TRUNC(PE_TIT.END_DAT_EXCL) = DATE '0001-01-01')
      LEFT JOIN DBAUNIMED.CEP CEP ON CEP.CEP_COD = NVL(PE.CEP_COD, PE_TIT.CEP_COD)
      LEFT JOIN DBAUNIMED.CIDADE CIDADE ON CIDADE.CIDAD_COD = CEP.CIDAD_COD
      LEFT JOIN DBAUNIMED.PREST PR_EXEC ON PR_EXEC.PREST_COD = GI.GUITE_COD_EXECUT
      LEFT JOIN DBAUNIMED.PESSOA P_EXEC ON P_EXEC.PES_COD = PR_EXEC.PREST_COD_PESSOA
      LEFT JOIN DBAUNIMED.UNIMED U_EXEC ON U_EXEC.UNI_COD = G.GUIA_COD_UNIMED_EXECUT
      LEFT JOIN DBAUNIMED.PESSOA P_UNIMED_EXEC ON P_UNIMED_EXEC.PES_COD = U_EXEC.UNI_PES_COD
      LEFT JOIN DBAUNIMED.ESPEC_MEDICA ESP_SOL ON ESP_SOL.ESPMD_COD = SOL.CD_ESPECIALIDADE
      LEFT JOIN DBAUNIMED.US8001 EXT
        ON EXT.US8UNIMED = G.US8UNIMED
        AND EXT.US8CODCONT = G.US8CODCONT
        AND EXT.US8CODUSU = G.US8CODUSU
        AND EXT.US8CODDEP = G.US8CODDEP
      LEFT JOIN DBAUNIMED.UNIMED U_INTERCAMBIO ON U_INTERCAMBIO.UNI_COD = EXT.US8UNIMED
      LEFT JOIN DBAUNIMED.PESSOA PES_INTERCAMBIO
        ON PES_INTERCAMBIO.PES_COD = U_INTERCAMBIO.UNI_PES_COD
      LEFT JOIN DBAUNIMED.REEMB REE ON REE.REEMB_NRO_SEQ = G.GUIA_NRO_SEQ_REEMB
      LEFT JOIN DBAUNIMED.REEMB_ITEM REEI
        ON REEI.REEMB_NRO_SEQ = REE.REEMB_NRO_SEQ
        AND REEI.REMBI_NRO_SEQ = GI.GUITE_NRO_SEQ
      LEFT JOIN DBAUNIMED.GUIA_FORA_REDE GFR ON GFR.GFR_COD_ID = G.GUIA_COD_GFR_ID
      LEFT JOIN DBAUNIMED.GUIA_FORA_REDE_ITEM GFRI
        ON GFRI.GFR_COD_ID = GFR.GFR_COD_ID
        AND GFRI.GFRI_NRO_SEQ = GI.GUITE_NRO_SEQ
      LEFT JOIN ESP_FORA_REDE_UNICA ESP_FORA_REDE
        ON ESP_FORA_REDE.ESPMD_COD_NRO_CBO = GFRI.GFRI_COD_CBO
      LEFT JOIN DBAUNIMED.ESPEC_MEDICA ESP_REEMB
        ON ESP_REEMB.ESPMD_COD = REE.REEMB_COD_ESPEC_MEDICA
      WHERE 1 = 1
        AND GI.GUITE_IND_STATUS = 'I'
      """.strip();

}
